import random

# Tau, represents how steep is the exponent decline
tau=100

# vij, Volume of a sale number j generated by user i, for now we suppose all transactions were made with the same volume.
vij=1

# platform fee
f=0.1

# Blocks number for the simulation
b=100
# Generating random blocks for each user. The block numbers generated for each user will represent those when the user has made a sale.

User1_blocks=sorted(random.sample(range(0, b), 1))
User2_blocks=sorted(random.sample(range(0, b), 3))
User3_blocks=sorted(random.sample(range(0, b), 5))
User4_blocks=sorted(random.sample(range(0, b), 10))
User5_blocks=sorted(random.sample(range(0, b), 15))

#List containing every block transacted by a user.
blocks_per_user=[User1_blocks,User2_blocks,User3_blocks,User4_blocks,User5_blocks]